### ISSUE TITLE
64 bit version of library

### ISSUE THREAD

**Issue by Crossverse** [Quintus/Automations#10]
You need change gem to load 64 bit library for 64 bit applications

**Comment by Crossverse** [comment]
May be better to use ffi instead of win32-api gem.

## My patch normal work for windows au3 functions. Other functions not tested.

change require "win32/api" into require 'ffi'

and

class AU3_Function 

into

  class AU3_Function  
   extend FFI::Library
    app_capacity=(['a'].pack('P').length)*8
    if app_capacity>32
        ffi_lib 'AutoItX3_x64.dll'
    else
        ffi_lib 'AutoItX3.dll'
    end
    ffi_convention :stdcall

```
#Creates a new AU3_Function object. Takes the +name+, the +arguments+ and the +returnvalue+ of 
#the function. +name+ will be prefixed by "AU3_" and the DLL is set to "AutoItX3.dll". 
#If you ommit the returnvalue, it's assumed to be of void type ('V'). 
def initialize(name, arguments, returnvalue = 'V')

  args=[]
  arguments.each_char do |val|
      t=case val  
      when 'V'; :void
      when 'I'; :int
      when 'L'; :int
      when 'P'; :pointer
      when 'S'; :pointer
      else raise "Unknown type #{val}"
      end
      args.push t
  end
  retval=case returnvalue
          when 'V'; :void
          when 'I'; :int
          when 'L'; :int
          when 'P'; :pointer
          when 'S'; :pointer
         else raise "Unknown type #{val}"
         end

  @func= AU3_Function.attach_function "AU3_#{name}", args, retval
end

def call *args
   @func.call *args
end
```

##   end

may be you need delete some othe win32-api  mentions

**Comment by Quintus** [comment]
I’m terribly sorry, but I don’t work on this library anymore, because I don’t do any serious Windows development anymore. If at all I will do a complete rewrite of this as a C extension.

Vale,
Quintus

**Comment by Quintus** [comment]
I don't work on this project anymore.
