### ISSUE TITLE
XDo::Keyboard.type does not work with single quotes

### ISSUE THREAD

**Issue by nhinds** [Quintus/Automations#11]
I know this library is old, but in case other people attempt to use it:

`XDo::Keyboard.type` passes its parameter directly into a single-quoted string, so attempting to include single quotes in the message results in either an error, missing quotation marks, or arbitrary shell execution.

```
XDo::Keyboard.type "Hello, 'world'"
Hello, world

XDo::Keyboard.type "Hello, 'world"
sh: 1: Syntax error: Unterminated quoted string

XDo::Keyboard.type "Hello, '; rm -fr /some/important/files #"
Hello, 
and now your files have been deleted
```

**Comment by Quintus** [comment]
I don't work on this project anymore.
