### ISSUE TITLE
Add send/post message/command

### ISSUE THREAD

**Issue by stevenheidel** [Quintus/Automations#7]
Add send_message/post_message/send_command/post_command to the Window class.

**Comment by Quintus** [comment]
#post_message and #send_message have now (version 0.1.2) been added to the AutoItX3::Window class. I wasn't able to find the slightest clue about how to implement the SendCommand() and PostCommand() functions, so unless you know how to implement them, you'll have to live without them.

**Comment by stevenheidel** [comment]
That's awesome. I tried to get those functions working because I thought I had done so before, but I didn't have any success either. There is very little difference between the two functions anyways.
