### ISSUE TITLE
Find window with regex or exclude title

### ISSUE THREAD

**Issue by cantonic** [Quintus/Automations#8]
Hi,

I need to wait for a window which does NOT contain a specific string in title. Is that possible in some way? Maybe through regex?

**Comment by Quintus** [comment]
First, note I’m not developing this actively anymore. I cannot guarantee that the au3 and xdo projects work at all anymore.

> Maybe through regex?

Yes. You can use a negative look-ahead construct such as:

```
# ruby -v: ruby 1.9.3p125 (2012-02-16 revision 34643) [x86_64-linux]
irb(main):001:0> str = "Foo"
=> "Foo"
irb(main):002:0> str.match(/Bar/)
=> nil
irb(main):003:0> str.match(/(?!Bar)/)
=> #<MatchData "">
irb(main):004:0> 
```

Vale,
Quintus

**Comment by Quintus** [comment]
I don't work on this project anymore.
