### ISSUE TITLE
Error in control.rb

### ISSUE THREAD

**Issue by Crossverse** [Quintus/Automations#9]
[1] pry(#Vers::Trading::Robo::Quik)> cont.focus
NameError: uninitialized constant AutoItX3::Control::AU3_Functino
from C:/Legacy/Ruby193/lib/ruby/gems/1.9.1/gems/au3-0.1.2/lib/AutoItX3/control.rb:134:in `focus'

**Comment by Crossverse** [comment]
you need replace AU3_Functino to AU3_Function

**Comment by Quintus** [comment]
I don't work on this project anymore.
